# Deploy to Azure Kubernetes Service
- task: InstallFortifySCA@7
  inputs:
    InstallerPath: 'C:\Users\giulia.di.nuzzo\Accenture\SecMaterials.ICEG - Documents\Vendor\Microfocus\Fortify SCA\Fortify_SCA_and_Apps_20.1.1_windows_x64.exe'
    VS2017: true
    VS2019: true
    LicenseFile: 'C:\Users\giulia.di.nuzzo\Accenture\SecMaterials.ICEG - Documents\Vendor\Microfocus\Accenture_EMEA_Static.txt'
    RunFortifyRulepackUpdate: false
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'e9e10d12-0bd0-43ec-84e4-efd6a6f0ee33'
  imageRepository: 'giuliadinuzzopipelinesjavascriptdocker'
  containerRegistry: 'fdrgdncr.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'fdrgdncr6203-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'giuliadinuzzopipelinesjavascriptdocker.fdrgdn-ns'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)

